### ISSUE TITLE
ggplot2 is not a required package for installd

### ISSUE THREAD

**Issue by AnthonyOfSeattle** [difuture-lmu/dsBinVal#15]
This is a small nit and probably won't be an issue for most people since most people will already have this installed. However, since plot the ROC curve is fairly standard, and is an advertised function of the package, ggplot2 should be included during automatic install.

**Comment by schalkdaniel** [comment]
That's a good point, thank you. I moved it to the `Imports` section.

**Comment by AnthonyOfSeattle** [comment]
LGTM
