### ISSUE TITLE
Improve technical details section of the paper

### ISSUE THREAD

**Issue by AnthonyOfSeattle** [difuture-lmu/dsBinVal#18]
I believe the technical details of the software paper need to be improved, and may benefit from incoporating some of the functionality descriptions in Section 6 of https://arxiv.org/abs/2203.10828 .

This does not need to go in depth, since the theory is laid out in the companion paper. It should really just focus on a short description of what helper functions are provided and what occurs in major functions.

I think a few points could go a long way.
- Provide a brief mention of the statistical functions which are included and how they can be used on a given project, and why.
- Mention that data is returned from the server twice in the roc_glm function calls and note the DP step taken to ensure this is safe.
- Mention that individual functions attempt to prevent accidental disclosures when data is not sufficient.
- Provide a description of the tests done in the package and how they demostrate the safety of the methods.

**Comment by schalkdaniel** [comment]
Thanks for the comment! It is indeed a good point to describe the methods a little more precisely. I have adapted the paper for this purpose and added a new paragraph and add two sentences in to the `Technical Details`:

---

## Functionality

The integration of the package into the DataSHIELD framework hence extends its functionality and allows users to assess the discrimination and calibration of a binary classification model without harming the privacy of individuals. Based on privacy-preserving distributed algorithms [@schalk2022rocglm], the assessing the discrimination is done by the `dsROCGLM()` function that calculates a ROC curve based on the ROC-GLM as well as an AUC with CI. The calibration is estimated distributively using the functions `dsBrierScore()` and `dsCalibrationCurve()`. Additional helper functions, namely `dsConfusion()` or `dsL2Sens()`, can be used to calculate several measures, e.g. sensitivity, specificity, accuracy, or the F1 score, from the confusion matrix or the L2-sensitivity. Note that measures from the confusion matrix may be disclosive for specific thresholds and are therefore checked and protected by DataSHIELDs privacy mechanisms. During the call to `dsROCGLM()`, parts of the data set are communicated twice, first, to calculate the ROC-GLM based on prediction scores, and second, to calculate the CI of the AUC. In both steps, the information is protected by differential privacy to prevent individuals from re-identification. The amount of noise generated for differential privacy is carefully chosen based on a simulation study that takes the variation of the predicted values into account. We refer to the [README](https://github.com/difuture-lmu/dsBinVal) file of the repository for a demonstration and usage of the functionality.

__Technical details:__ To ensure the functioning of our package on DataSHIELD, it is constantly unit tested on an active DataSHIELD [test instance](opal-demo.obiba.org). The reference, username, and password are available at the [OPAL documentation](opaldoc.obiba.org/en/latest/resources.html) in the "Types" section. Parts of the tests also cover checks against privacy breaches by attempting to call functions with data sets that do not pass the safety mechanisms of DataSHIELD. Hence, individual functions attempt to prevent accidental disclosures when data is not sufficient to ensure privacy.

---

**Comment by AnthonyOfSeattle** [comment]
Thank you for the prompt edit to this. I will leave a separate issue with a couple copy edit recommendations for this, but I believe this fulfills my request.
